### ISSUE TITLE
java.lang.NoClassDefFoundError: dalvik.system.BaseDexClassLoader

### ISSUE THREAD

**Issue by yaoyinbear** [liyuming1978/NativeLibCompression#1]
部分机型上会出现错误：
java.lang.NoClassDefFoundError: dalvik.system.BaseDexClassLoader

log如下：
E/AndroidRuntime(13380): FATAL EXCEPTION: main
E/AndroidRuntime(13380): java.lang.NoClassDefFoundError: dalvik.system.BaseDexClassLoader
E/AndroidRuntime(13380):    at com.library.decrawso.UtilsFunc.HackSystemICS(UtilsFunc.java:87)
E/AndroidRuntime(13380):    at com.library.decrawso.UtilsFunc.HackLibPath(UtilsFunc.java:77)
E/AndroidRuntime(13380):    at com.library.decrawso.DecRawso.<init>(DecRawso.java:451)
E/AndroidRuntime(13380):    at com.library.decrawso.DecRawso.NewInstance(DecRawso.java:865)

测试机环境：
酷派5860+
刷了甜椒刷机上提供的“酷派5860+全透美化ROM”
Android 4.1.4

**Comment by yaoyinbear** [comment]
在云测上的测试结果显示貌似有不少机型出现这个错误
HTC  A9191 2.3.3
HTC  S510e 2.3.3
HTC  S710d 2.3.4
HTC  T-Mobile G2 2.3.3
HTC  X715e 2.3.4
HTC  Z710e 2.3.4
步步高  E1 2.3.5
海信  HS-E912 2.3.6
宏基  A100 3.2.1
华为  C8650+ 2.3.6
华为  U8650 2.3.5
金立  GN380 2.3.4
垦鑫达  KXD I9300 4.0.1
酷比  A109 2.3.6
酷派  8150 2.3.7
联想  P70 2.3.5
米格  MG2 2.3.6
摩托罗拉  Defy+ 2.3.6
摩托罗拉  MT680 2.3.7
摩托罗拉  MZ606 3.1
摩托罗拉  XT319 2.3.5
摩托罗拉  XT531 2.3.5
索爱  MT15i 2.3.4
索爱  ST15i 2.3.3
天语  E619 2.3.6
唯掌  NJ905 4.1.1
中兴  N855D 2.3.6
中兴  U880 2.3.7
斐讯  FWS610 2.3.7
斐讯  FWS710 2.3.7
斐讯  FWS910 2.3.7
斐讯  I310v 2.3.5

**Comment by liyuming1978** [comment]
没事的， 有4个函数
                HackSystemICS(pname);  
        HackSystemLow1(pname);
        HackSystemLow2(pname);
        HackSystemLow3(pname);
只要有其中一个成功就成， 具体的要看看那个demo运行是否正确  或者看log，看看是否有一个成功

**Comment by liyuming1978** [comment]
是因为 HackLibPath这个函数修改了， 以前是根据机型的版本调用某个函数， 后来发现有问题，干脆4个挨个试，成功一个就ok

**Comment by yaoyinbear** [comment]
我想说的是，因为这个错误，貌似大部分2.3的安卓系统下，应用都直接crash了。也有部分4.x的系统出现此问题。

**Comment by liyuming1978** [comment]
多谢， 改正上传了， 添加了catch (NoClassDefFoundError e)  这个error居然不属于Exception
一般情况下应该上报  NoSuchFieldException 
为了保险： 使用java.lang.Error 父类涵盖的更广

**Comment by liyuming1978** [comment]
云测上有个别应用显示  demo die， 好像是和demo里面的service创建有关。

**Comment by liyuming1978** [comment]
酷派 5890 4.1.2 可能损失 54 万用户
堆栈日志运行错误 (@ 1分10秒) ： Process com.example.compressdemo died.
摩托罗拉 XT702 2.2.1 可能损失 31 万用户
堆栈日志运行错误 (@ 1分1秒) ： Process com.example.compressdemo died.
信得乐 A8-T1 4.3 可能损失 18 万用户
堆栈日志运行错误 (@ 1分6秒) ： Process com.example.compressdemo died.
优思 U558 4.1.2 可能损失 10 万用户
堆栈日志运行错误 (@ 1分4秒) ： Process com.example.compressdemo died.
智酷 X5--3G 4.1.2 可能损失 10 万用户
堆栈日志运行错误 (@ 0分52秒) ： Process com.example.compressdemo died.

**Comment by liyuming1978** [comment]
修改了 mainactivity          switchto(); 去掉了这个//this.finish(); 
这5个机器就ok了

**Comment by yaoyinbear** [comment]
我在云测上测试的是我自己写的app，里面没有用到service，所以与demo无关。如错误log所示，应该是大部分的2.3系统并没有 dalvik.system.BaseDexClassLoader 这个类。 参考代码的话，2.3应该是调用 HackSystemLow1里的PathClassLoader。 我本来也是想直接catch java.lang.Error来解决的，不过开发手册上明确不建议catch任何Error，后来就没多想了。不过就结果来说，目前应该算是解决了2.3上的crash问题了。只是，如果有新的系统或者更老的系统，在4次HackSystem调用中都catch Error了的话，没有个明确的log输出，恐怕会给后续的使用者带来一定困扰，因为4次过了后面只能抛出找不到so的异常了吧。

**Comment by liyuming1978** [comment]
这个也是没有办法的事情， 所以我虽然catch了error，但是把error都输出了， 如果所有的so加载都能使用System.load(DecRawso.GetInstance().GetPath("helloone"));  那么这个hack就不需要， 但是大部分有第三方sdk， 所以必须修改系统loadlibrary的路径， 这已经是非标准办法了。

至少目前hack已经覆盖到 5.0的系统。 云测上 我测试了所有的系统， 目前这个hack工作正常
