### ISSUE TITLE
请教一个问题System.loadlibrary的问题

### ISSUE THREAD

**Issue by sxh1017** [liyuming1978/NativeLibCompression#2]
你好，想请教一个问题，System.loadlibrary(***) 现在是怎么进行兼容的呢，我看了so最终是解析在data/data/com.example.compressdemo/files/DecRawsoLib/ 这个目录下的，System.loadlibrary加载的路径好像不包括这个目录，想请教下，是如何实现的呢？

**Comment by liyuming1978** [comment]
请查看 HackLibPath 这个函数.
